GRANT USAGE ON SCHEMA public TO match_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO match_app;
REVOKE UPDATE, DELETE ON TABLE "AuditEvent" FROM match_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO match_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO match_app;
